before_script:
    - cp config/travis.database.yml config/database.yml
    - rm .rspec
    - mysql -e 'create database note2task_test;'
    - echo "USE mysql;\nCREATE USER 'test'@'localhost' IDENTIFIED BY 'foobar';\n" | mysql -u root
    - echo "grant all privileges on *.* to test@localhost identified by 'foobar';\n" | mysql -u root
    - echo "FLUSH PRIVILEGES;\n" | mysql -u root
    - "rake db:migrate RAILS_ENV=test"