before_script:
    - mysql -e 'create database `everdo-test`;'
    - echo "USE mysql;\nCREATE USER 'test'@'localhost' IDENTIFIED BY 'foobar';\n" | mysql -u root
    - echo "USE mysql;\n grant all privileges on `everdo-test`.* to test@localhost identified by 'foobar';\n" | mysql -u root
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('foobar') WHERE user='test';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - "rake db:migrate RAILS_ENV=test"