development:
  adapter: mysql2
  database: note2task
  username: root
  password: 'M!tten#2'

test:
  adapter: mysql2
  database: note2task_test
  username: test
  password: 'foobar'

production:
  adapter: mysql2
  database: note2task
  username: root
  password: 'M!tten#2'
