# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: everdo
  username: root
  password: 'M!tten#2'

test:
  adapter: mysql2
  database: everdo-test
  username: test
  password: 'foobar'

production:
  adapter: mysql2
  database: everdo
  username: root
  password: 'M!tten#2'
